server:
  port: 8081
  servlet:
    context-path: /restaurant

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://mysql:3306/restaurant}
    username: ${DBMS_PASSWORD:root}
    password: ${DBMS_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
