server:
  port: 8081
  servlet:
    context-path: /shoeshop

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shoeshop"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
